### ISSUE TITLE
Change appearance of MM Explorer side bar

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaExplorer#10]
Use appearance similar to what used in 4DN-Data Portal
![image](https://github.com/WU-BIMAC/MicroMetaExplorer/assets/4050585/2813597a-37a3-4a6f-8178-6e0632771c8d)

**Comment by strambc** [comment]
- [ ] Name of category - Left Aligned
- [ ] Number of items in the category - Right Aligned
- [ ] Assets list - 
-- [ ] remove blue background
-- [ ] text in grey that becomes black with mouse hover

**Comment by Akramhar** [comment]
done in the new version
