### ISSUE TITLE
Issues with GUI sidebar

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaExplorer#13]
Except "Type" all other items are summarized under the wrong category. 
E.g.,

- Manufacturer --> uses list of stand Category (Interted, Upright)
- Model --> uses Manufacturer list
- Stand Type --> uses Model

It looks like it is shifted 

![image](https://github.com/WU-BIMAC/MicroMetaExplorer/assets/4050585/42ca3c67-0298-49fb-8fdc-8dde9383933c)

![image](https://github.com/WU-BIMAC/MicroMetaExplorer/assets/4050585/b624780c-2482-4dc0-9f69-f36446dabb21)

**Comment by Akramhar** [comment]
should be fixed in explorer 1.0.3 - electron 2.0.3
