### ISSUE TITLE
REQUEST FOR FUNCTIONALITY /GUI CHANGES

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaExplorer#14]
- [x] Invert the order of "Catalog Number" and "Origin" under "Microscope Stand Details"

![image](https://github.com/WU-BIMAC/MicroMetaExplorer/assets/4050585/38e55cb9-8588-44e1-9081-3875aa94bf7f)

- [ ] In the side bar when the names of items are too long, they cannot be seen: is it possible to have the sidebar be resizable (expanded laterally)? If not we have to find another solution, e.g., lateral scroll, or (less favored) wrap text

![image](https://github.com/WU-BIMAC/MicroMetaExplorer/assets/4050585/6c5ef865-1b45-4fe3-9c4f-663a4caf29e9)

**Comment by strambc** [comment]
- [ ] When 2 microscopes are selected to compare, and user selects one to open, the user has to click on Home to find it again and launch in MMA. When going back to Home it would be a good idea to maintain selection that was used for Compare

**Comment by strambc** [comment]
- [ ] Would it be possible to launch "Open in MMA" from "Compare" window?

**Comment by Akramhar** [comment]
Point 2 is fixed with wrap text atm for Explorer 1.0.3 - Electron 2.0.3

**Comment by strambc** [comment]
Point 2: text wrap-around does not appear to work

**Comment by strambc** [comment]
Point 3 moved to new issue #19
