### ISSUE TITLE
TransmittanceRange, WaveLenghtRange etc. are missing

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaExplorer#15]
Filter, Dichroics, Detector are missing information related to TransmittanceRange, and WavelenghtRange modules respectively

Same applies to all other components that have sub-modules (LED-Module, IlluminationWavelenghtRange etc.)

**Comment by Akramhar** [comment]
should be fixed in explorer 1.0.3 - electron 2.0.3
