### ISSUE TITLE
Issues with items displayed in Compare mode

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaExplorer#16]
When 3 items are available only 2 is displayed and there is no scrolling arrows
This was observed with Objectives

This does not apply to 4 items or more

It appears with 3 or less items

When 1 item is present in second MIcroscope selected also gives issues such as this:

![image](https://github.com/WU-BIMAC/MicroMetaExplorer/assets/4050585/c90c96fd-9f4f-458f-b535-e72a1329b0db)

**Comment by strambc** [comment]
![image](https://github.com/WU-BIMAC/MicroMetaExplorer/assets/4050585/4d752b5d-63bc-44bf-9f47-175c7a185146)

**Comment by Akramhar** [comment]
should be fixed in 2.0.3
