### ISSUE TITLE
[QUESTIONS] MMExplorer questions

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaExplorer#5]
![image](https://github.com/WU-BIMAC/MicroMetaApp-React/assets/4050585/230c4673-4b13-4117-b5f6-818dc924fc5e)

- [x] Why are the fields below the microscope name in the general Exploerer view empty?

**Comment by Akramhar** [comment]
should be fixed in version 1.01

**Comment by Akramhar** [comment]
- [ ] move tier to detail
- [ ] move type to column
- [ ] Rename stand type to configuration
- [ ] add number of light sources to detail
- [ ] add number of objectives to detail
- [ ] add number of filters to detail

**Comment by Akramhar** [comment]
added all + number Dichroics & number Lenses
