### ISSUE TITLE
[NEW FEATURE] MM EXPLORER COMPARE - vaious GUI issues

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaExplorer#6]
Microscope viewer comparison view

- [x] do not collapse sections when scrolling sideways
- [x] align name of Microscope to center of each columns
- [x] change "Metadata" to "Field Name"

![image](https://github.com/WU-BIMAC/MicroMetaApp-React/assets/4050585/45200018-0007-428e-87b7-4481ca4fe2c3)

**Comment by Akramhar** [comment]
should be fixed in 1.0.1, issue 2 is still a bit wonky for my taste my want to consider changing the library we use for table handling in the next iteration
